package com.pages;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Date;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.openqa.selenium.WebDriver;

public class CensusInfo {
	
	public CensusInfo() {
		Relation = new String[10];
		Income = new ArrayList<IncomeInfo>();
    }
	public String Zipcode;
	public String Zipcode2;
	public String Zipcode3;
	public String RLCZipcode;
	public String Statecode;
	public String Gender;
	public String Language;
	public String DOB;
	
	public String DOBDep1;
	public String HHDepedentSSN;
	public String DOBDep2;
	public String DOBDep3;
	public Boolean Tobacco;
	public Boolean IsPregnant;
	public String NumOfBabiesExpecting;
	public String[] Relation;
	public String Firstname;
	public String Dep1Firstname;
	public String Dep2Firstname;
	public String Dep3Firstname;
	public String Middlename;
	public String Lastname;
	public String Email;
	public String Phone;
	public String AddressLine1;
	public String AddressLine2;
	public String MaritalStatus;
	public String IsLivingOutsideTemporarily;
	public String LivingAddress;
	public String SSN;
	public String DepSSN;
	public String Dep2SSN;
	public String Dep3SSN;
	public String Earnings;
	public String ApplicantIncome;
	public String SpouseIncome;
	public String SpouseFirstname;
	public String SpouseLastname;
	public String HHApplicantSSN;
	public String HHSpouseSSN;
	public ArrayList<IncomeInfo> Income;
//	public ArrayList<DeductionInfo> Deduction;
	public String EmployerName;
	public String Employerphn;
	public String DeductionAmount;
	public String CoverageName;
	public String Policynumber;
	public String CurrentCoverage;
	public String ReasonLifeEvent;
	public String MarriageDate;
	public String ClaimDependent;
	public String DependentDisability;
	public String IsMedicaidOrCHIPCoverageEnded;
	public String IsMedicaidOrChildHealthNotEligible;
	public String IncomeDiscrepancy;
	public String IncomeDiscrepancyReason;
	public String Disability;
	public String DisabilityMember;
	public String LastDateorCHIPcoverage;
	public String LoseQHC;
	public String Member;
	public String MovedDate;
	public String SeekFinAssistance;
	public String DoesAnyConditionAppyNo;
	public String TribeState;
	public String Tribename;
	public String Priorcoverage;
	public String TribalAmt;
	public String Needcoverage;
	public String HouseholdSize;
	public String MedicaidDeniedDate;
	public String MailingYesNobtn;
	public String Groupsplit;
	public String Startdate;
	public String Enddate;
	public String Addcoverageperson;
	public String WillAnyOneLoseQHC;
	public String IsPlanningToFileTaxJointly;
	public String IsClaimingAnyDependents;
	public String IsPlanningToFileTax;
	public String TakingCareAnyOtherChildren;
	public String IsLivingWithParents;
	public String IsClaimedAsDependent;
	public String EstimateIncomeInd;
	public String EstimateIncomeAmt;
	public String IsNaturalizedOrDerivedCitizen;
	public String IsUSCitizen;
	public String AddSomeone_AsDependent;
	public String AddSomeone_AsDependent_Fname;
	public String AddSomeone_AsDependent_Lname;
	public String AddSomeone_AsDependent_Gender;
	public String AddSomeone_AsDependent_Dob;
	public String AddSomeone_AsDependent_Fname2;
	public String AddSomeone_AsDependent_Lname2;
	public String AddSomeone_AsDependent_Gender2;
	public String AddSomeone_AsDependent_Dob2;
	public String Income1;
	public String TobaccoUser;
	public String Tobacco1;
	public String NumberOfRelationships;
	public String NumberOfMembers;
	public String Income_Sources;
	public String NaturalizationCertificateAlienNumber;
	public String NaturalizationCertificate;
	public String IsHaveEligibleImigrationStatus;
	public String DependentDailyAct;
	public String DisabilityMember1;
	public String DisabilityMember2;
	public String Amount1;
	public String DeductionType;
	public String TribalIncome;
	public String Enddate_back_95;
	public String EnlastMonth;
    public String LastName;
    public String LastName1;
	public String FirstName;
	public String ListName;
	public String TemplateName;
	public String Despo;
}
